### ISSUE TITLE
As soon as...

### ISSUE THREAD

**Issue by jszgz** [hellock/scale-time-lattice#6]
We will release the code as soon as we finish the cleaning. Our implementation is based on PyTorch and we will release both training and testing code

**Comment by tzjtatata** [comment]
finally...



---Original---

**Comment by johnny-salz** [comment]
Awesome! If this stuff is as good as in paper than is was we'll worth
waiting :)

**Comment by ZhiweiYan-96** [comment]
Hi, is there any progress?
